# Generated by Django 2.2.11 on 2021-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_phonenumberfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
